##############################	Nearpedia ##############################

#Menu
NEARPEDIA.menu.menuFlight = 	//*[@id="navbarSupportedContent"]/ul/li[2]/a

#Nearpedia
NEARPEDIA.nearpedia.cmbFlightFrom = flight-from
NEARPEDIA.nearpedia.cmbFlightTo = flight-to
NEARPEDIA.nearpedia.txtDeparting = departing
NEARPEDIA.nearpedia.txtReturning = returning
NEARPEDIA.nearpedia.btnSearch = button[class="btn btn-primary button-ns"]
NEARPEDIA.nearpedia.cmbSort = sort