############################## SauceDemo ##############################
# Login page
SAUCEDEMO.login.txtUsername=user-name
SAUCEDEMO.login.txtPassword=password
SAUCEDEMO.login.btnLogin=login-button
# Inventory page
SAUCEDEMO.inventory.title=title
SAUCEDEMO.inventory.btnAddToCart=add-to-cart-sauce-labs-backpack
# Cart page
SAUCEDEMO.cart.btnCart=shopping_cart_container
SAUCEDEMO.cart.btnCheckout=checkout
# Checkout step one
SAUCEDEMO.checkout.txtFirstName=first-name
SAUCEDEMO.checkout.txtLastName=last-name
SAUCEDEMO.checkout.txtZipCode=postal-code
SAUCEDEMO.checkout.btnContinue=continue
# Checkout step two
SAUCEDEMO.checkout.btnFinish=finish
# Checkout complete
SAUCEDEMO.checkout.confirmHeader=complete-header